#!/bin/bash
#
# Simple script to find all lines marked with "#.*TODO:" (regex) in files tracked
# by a git repo
#

# Prevent whitespace in filenames from breaking search
OIFS="$IFS"
IFS=$'\n'

if [ "$(git rev-parse --is-inside-work-tree 2> /dev/null)" ]; then
  git_root="$(git rev-parse --show-toplevel)"
  pushd "$git_root" > /dev/null || exit

  # Markdown table header
  printf "| File | Line | Comment |\n| ---- | ---- | ------- |\n" > TODO.md

  # Use the Git tracked files as the ones to search (inately follows .gitignore's)
  grep -rnw $(git ls-files) -e "#.*TODO" \
    | awk -F':' '{ printf "| ["; system("basename " $1 " | head -c -1"); printf "]"; print "(" $1 "#L" $2 ")" " | " $2 " | " $4 " |" }' \
    | tee -a TODO.md

  popd > /dev/null || exit
else
  echo "Not in a git repo, exiting..."
fi

IFS="$OIFS"
