#!/bin/bash
#
# Useful for simple projects looking to add->commit->push in one step
#

if [ -z "$1" ]; then
  echo -e "\033[1;31mError:\033[0m Pass a commit message"
  exit 1
fi

if [ "$(git rev-parse --is-inside-work-tree 2> /dev/null)" ]; then
  git_root="$(git rev-parse --show-toplevel)"
  pushd "$git_root" > /dev/null || exit
  git add -A
  git commit -m "$1"
  git push
  popd > /dev/null || exit
fi
