#!/bin/bash
#
# More aggressive removal of DOS line endings found in a repo
# Could be useful in git hook, replace find pattern based on filetypes

if [ $(git rev-parse --is-inside-work-tree 2> /dev/null) ]; then
  git_root="$(git rev-parse --show-toplevel)"
  pushd ${git_root} > /dev/null
  # find files w/DOS line-endings and pipe to 'dos2unix' to convert to Unix EOLs
  find . -type f \( -iname \*.vhd -o -iname \*.v \) -exec file "{}" ";" | grep CRLF | sed 's/:.*//' | xargs dos2unix
  # replace any Posix-defined trailing whitespace chars from selected files
  find . -type f \( -iname \*.vhd -o -iname \*.v \) -exec sed --in-place 's/[[:space:]]\+$//' {} \+
  # for tracked files, check if we made any changes other than whitespace/EOL related
  if [[ $(git diff --ignore-space-at-eol -b -w HEAD) ]]; then
    echo "Diff indicates actual code was changed beyond whitespace/EOL changes; run 'git diff' to verify any changes or revert back to previous"
  else
    echo "Success"
  fi
  popd > /dev/null
fi
