#!/bin/bash
#
# Lists all blob objects in repo from smallest to largest
# https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history
# To remove large files from history see:
# https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository

usage() { echo -e 'Lists all blob objects in repo from smallest to largest.\nUsage:\n\tgit-list-large [-n <num_lines_to_display> ]'; exit; }

num_lines=10

if [ "$#" -eq 2 ]; then
  if [ "$1" = "-n" ]; then
    num_lines=$2
  else
    usage
  fi
elif [ "$#" -ne 0 ]; then
  usage
fi

if [ $(git rev-parse --is-inside-work-tree 2> /dev/null) ]; then
  git rev-list --objects --all \
    | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
    | sed -n 's/^blob //p' \
    | sort --numeric-sort --key=2 \
    | cut -c 1-12,41- \
    | $(command -v gnufmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest \
    | tail -n $num_lines
fi
