#!/bin/bash

# Colors for printing
BLU='\033[1;34m'
NC='\033[0m'

# change for differenct src directory
pushd ~/src > /dev/null || exit

# Iterate through directories in src/ and check git status
i=0
for d in */ ; do
  pushd "$d" > /dev/null || exit
  if [ "$(git rev-parse --is-inside-work-tree 2> /dev/null)" ]; then
    # Get remote (often 'origin')
    repoRemote="$(git remote)"
    # Get default branch from remote
    defBranch="$(git remote show "$repoRemote" | sed -n '/HEAD branch/s/.*: //p' )"

    oldOrigin="$(git remote get-url "$repoRemote")"
    if [[ $oldOrigin == git@* ]]; then # build git:// URL (no auth needed compared to SSH)
      # the path is done like since some git repos have more than 1 level of git
      # directory levels to traverse
      repoPath="$(echo "$oldOrigin" | awk -F[@/:] '{for(i=2;i<=NF;++i) printf "/"$i}')"
      git fetch "git:/$repoPath" &> /dev/null
    else # no authentication needed
      git fetch "$repoRemote" > /dev/null
    fi
    gitDiffStr="$(git diff HEAD "$repoRemote/$defBranch")"
    if [ -n "$gitDiffStr" ]; then
      echo -e "\n${BLU}[$d]${NC}"
      git diff HEAD "$repoRemote/$defBranch"
      ((i++))
    fi;
  fi;
  popd > /dev/null || exit
done

if [ "$i" -gt 0 ]; then
  # NOTE: requires [NerdFonts](https://github.com/ryanoasis/nerd-fonts)
  printf "  Git Repo Updates Available: %s" "$i" > /tmp/sys_git_updates
else
  printf "" > /tmp/sys_git_updates
fi;

popd > /dev/null || exit

