#!/bin/bash
# File              : diff_configs
# Author            : John Gentile <johncgentile17@gmail.com>
# Date              : 29.12.2017
# Last Modified Date: 05.01.2018
# Last Modified By  : John Gentile <johncgentile17@gmail.com>
#
# Shell script to update all needed development tools
# Run as intended user
#

# Colors for printing
BLU='\033[1;34m'
NC='\033[0m'

echo -e "${BLU}[.gitconfig]${NC}"
diff ./configs/.gitconfig ~/.gitconfig
echo -e "${BLU}[.bashrc]${NC}"
diff ./configs/.bashrc ~/.bashrc
echo -e "${BLU}[.bash_profile]${NC}"
diff ./configs/.bash_profile ~/.bash_profile
echo -e "${BLU}[.inputrc]${NC}"
diff ./configs/.inputrc ~/.inputrc
echo -e "${BLU}[Konsole Profile]${NC}"
diff ./configs/konsole/JG_profile.profile ~/.local/share/konsole/JG_profile.profile
echo -e "${BLU}[.vimrc]${NC}"
diff ./configs/.vimrc ~/.vimrc
echo -e "${BLU}[vim color schemes]${NC}"
diff ./configs/gmonokai.vim ~/.vim/colors/gmonokai.vim
echo -e "${BLU}[.tmux.conf]${NC}"
diff ./configs/.tmux.conf ~/.tmux.conf
echo -e "${BLU}[Ranger rc.conf]${NC}"
diff ./configs/rc.conf ~/.config/ranger/rc.conf
diff ./configs/scope.sh ~/.config/ranger/scope.sh
echo -e "${BLU}[.muttrc]${NC}"
diff ./configs/.muttrc ~/.muttrc
