#!/bin/bash
# File              : git_statuses
# Author            : John Gentile <johncgentile17@gmail.com>
# Date              : 14.01.2018
# Last Modified Date: 21.04.2018
# Last Modified By  : John Gentile <johncgentile17@gmail.com>
# Automate checking git status of `src` directories

# Colors for printing
BLU='\033[1;34m'
NC='\033[0m'

pushd ~/src

# Iterate through directories in src/ and check git status
for d in */ ; do
  pushd $d &> /dev/null
  echo -e "\n${BLU}[$d]${NC}"
  git status -s
  popd &> /dev/null
done

popd
