#!/bin/bash
# File              : git_pulls
# Author            : John Gentile <johncgentile17@gmail.com>
# Date              : 02.01.2018
# Last Modified Date: 21.04.2018
# Last Modified By  : John Gentile <johncgentile17@gmail.com>
#
# Automate checking `git pull` of `src` directories

# Colors for printing
BLU='\033[1;34m'
NC='\033[0m'

# Find if ssh-agent process is already running. If not, start it and auto add
# private key from default location. If running do nothing. If more than one
# process running, kill last one
case "$(pidof ssh-agent | wc -w)" in
  0) echo -e "\n${BLU}Restarting ssh-agent:${NC}"
    eval 'ssh-agent'
    ;;
  1) echo -e "\n${BLU}ssh-agent already running $(pidof ssh-agent)${NC}"
    ;;
  *) echo -e "\n${BLU}Removed double process of ssh-agent${NC}"
    kill $(pidof ssh-agent | awk '{print $1}')
    ;;
esac

echo "Adding private key from default location:"
ssh-add

mkdir -p ~/src
pushd ~/src &> /dev/null

# iterate through directories in src/ directory to automatically pull
for d in */ ; do
  echo -e "\n${BLU}[$d]${NC}"
  pushd $d &> /dev/null
  git pull
  popd &> /dev/null
done

# Use GitHub REST API to get list of repos and automatically clone them into
# src/ directory
# Iterate through PAGE variable if more than 100 repos per user
PAGE=1
curl "https://api.github.com/users/JohnnyGOX17/repos?page=$PAGE&per_page=100" | grep -e 'git_url*' | cut -d \" -f 4 | xargs -L1 git clone
curl "https://api.github.com/orgs/Gent-Systems/repos?page=$PAGE&per_page=100" | grep -e 'git_url*' | cut -d \" -f 4 | xargs -L1 git clone

popd
