#!/bin/sh

insLoc=/usr/local/bin/

cp ./dev_utils/generate-sitemap           $insLoc
cp ./dev_utils/lsusb_sysdevpath           $insLoc
cp ./dev_utils/git/git-print-TODOs        $insLoc
cp ./dev_utils/git/git-rewrite-author     $insLoc
cp ./dev_utils/git/git-status-src-dirs    $insLoc
cp ./dev_utils/git/git-update-src-dirs    $insLoc
cp ./dev_utils/git/git-rm-dos-whitespace  $insLoc
cp ./dev_utils/git/git-acp                $insLoc
cp ./dev_utils/git/git-list-large         $insLoc
cp ./dev_utils/git/git-fix-ssh-origin-url $insLoc
cp ./dev_utils/git/git-check-remote-changes $insLoc
cp ./dev_utils/check-python-outdated      $insLoc

cp ./sys_utils/backup_data                $insLoc
cp ./sys_utils/mvrms                      $insLoc
cp ./sys_utils/scrot-screenshot           $insLoc
cp ./sys_utils/sys-backup                 $insLoc
cp ./sys_utils/tmux_mem_cpu               $insLoc

echo "Scripts installed to $insLoc"
