#!/bin/bash
# File              : install_packages_apt
# Author            : John Gentile <johncgentile17@gmail.com>
# Date              : 12.12.2017
# Last Modified Date: 05.01.2018
# Last Modified By  : John Gentile <johncgentile17@gmail.com>
#
# Shell script to install all needed development tools and software
# Run as root/sudo
#

# Colors for printing
RED='\033[1;31m'
BLU='\033[1;34m'
NC='\033[0m'

# Path to temporary installation directory
InsPath=/tmp/jginstall/

if [[ $EUID -ne 0 ]]; then
  printf "${RED}Error: This script must be run as root${NC}\n"
  exit 1
fi

if [[ $1 = "-h" ]]; then
  echo "Usage: ./install_packages_apt [-a]"
  echo -e "\t-a,\tInstall all packages including source based ones that may be redundant"
  exit 0
fi

printf "\n${BLU}Install started at:${NC} $(date)\n"
printf "${BLU}Creating temp directory at: ${NC}$InsPath\n\n"
mkdir -p $InsPath
pushd $InsPath

#
# Update and upgrade
#
echo -e "\n${BLU}$(date +"%T"):${NC} Updating and Upgrading current apt repos\n"
apt update
# Use dist-upgrade to smart dependency changing and conflict resolution
apt -y dist-upgrade

#
# Install Basic Development Parts & General Tools
#
echo -e "\n${BLU}$(date +"%T"):${NC} Installing any apt applications\n"
apt-get -y install autoconf \
  automake \
  build-essential \
  bzip2 \
  checkinstall \
  cifs-utils \
  cmake \
  curl \
  exuberant-ctags \
  ffmpegthumbnailer \
  g++ \
  gcc \
  git \
  highlight \
  htop \
  ike \
  irssi \
  lm-sensors \
  make \
  mutt \
  nano \
  python-dev \
  python3-dev \
  ranger \
  shellcheck \
  tcl \
  tmux \
  unrar \
  urlview \
  visualboyadvance \
  visualboyadvance-gtk \
  w3m \
  w3m-img \
  wget \
  xclip

# Install npm packages requiring admin rights
echo -e "\n${BLU}$(date +"%T"):${NC} Installing npm applications\n"
npm install -g grunt-cli \
  tmux-cpu \
  tmux-mem

# Source-based installs
if [[ $1 = "-a" ]]; then
  # Install Clang 5.0
  echo -e "\n${BLU}$(date +"%T"):${NC} Installing Clang 5.0 from source\n"
  # from https://askubuntu.com/questions/905205/installing-clang-5-0-and-using-c17
  # remove list file if already there
  [ -e /etc/apt/sources.list.d/llvm.list ] && rm /etc/apt/sources.list.d/llvm.list 
  echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main" > /etc/apt/sources.list.d/llvm.list 
  wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  apt-get update
  apt-get -y install clang-5.0 \
    clang-5.0-doc \
    clang-5.0-examples \
    lldb-5.0 \
    lld-5.0

  # Install Vim from src
  echo -e "\n${BLU}$(date +"%T"):${NC} Installing Vim from source\n"
  apt remove vim vim-common vim-runtime gvim
  git clone https://github.com/vim/vim.git
  cd vim
  ./configure --with-features=huge \
    --enable-multibyte \
    --enable-rubyinterp=yes \
    --enable-pythoninterp=yes \
    --enable-perlinterp=yes
  # if weird, run this process as regular user then run `make install` as sudo
  make VIMRUNTIMEDIR=/usr/local/share/vim/vim80
  make install
  # sometimes `sudo` is removed with vim
  apt install -y sudo
  hash vim

  # Go- remove older Go 1st (if there) then install (note DL link should be
  # checked for updates)
  echo -e "\n${BLU}$(date +"%T"):${NC} Installing Go from source\n"
  rm -rf /usr/local/go
  wget https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
  tar -C /usr/local/ -xzf go1.9.linux-amd64.tar.gz
  rm -f go1.9.linux-amd64.tar.gz

  # Install Rust
  echo -e "\n${BLU}$(date +"%T"):${NC} Installing Rust from source\n"
  curl https://sh.rustup.rs -sSf | sh

  # Install powerline fonts for Vim plugins
  # https://powerline.readthedocs.io/en/master/installation/linux.html#fonts-installation

  # Install Wine stable 2.0+ and Play on linux
  echo -e "\n${BLU}$(date +"%T"):${NC} Installing Wine 2.0+\n"
  dpkg --add-architecture i386
  wget -nc https://dl.winehq.org/wine-builds/Release.key
  apt-key add Release.key
  apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
  rm Release.key
  apt-get update
  apt-get install -y --install-recommends winehq-stable
  apt-get install -y playonlinux

  # Install VirtualBox 5.2 from repo
  echo -e "\n${BLU}$(date +"%T"):${NC} Installing VirtualBox 5.2.x for Ubuntu 16.04 (Xenial)\n"
  # Use repo for Ubuntu 16.04 (Xenial); remove list file if already there
  [ -e /etc/apt/sources.list.d/virtualbox.list ] && rm /etc/apt/sources.list.d/virtualbox.list
  echo "deb http://download.virtualbox.org/virtualbox/debian xenial contrib" > /etc/apt/sources.list.d/virtualbox.list
  wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  apt-get update
  apt-get install virtualbox-5.2 dkms
  echo -e "Install success but ${RED}VirtualBox Extension Pack may need to be installed still${NC}"

  # Install facebook PathPicker
  # Note: this app install location can change
  pushd /usr/local/
  git clone https://github.com/facebook/PathPicker.git
  # Note: absolute path could be changed to relative $(pwd) to be more dynamic
  ln -s /usr/local/PathPicker/fpp /usr/local/bin/fpp
  popd

  # Create (if needed) mutt dirs & other files
  mkdir -p ~/.mutt/jgentile/headers
  mkdir -p ~/.mutt/jgentile/bodies
  touch ~/.mutt/certificates
  # get solarized color scheme
  wget -O ~/.mutt/mutt-colors-solarized-dark-256.muttrc https://raw.githubusercontent.com/altercation/mutt-colors-solarized/master/mutt-colors-solarized-dark-256.muttrc
  
fi

# Clean & exit
printf "\n${BLU}$(date +"%T"):${NC} Deleting temp directory at $InsPath\n"
popd
rm -rf $InsPath*
apt -y autoremove
printf "\n${BLU}$(date +"%T"):${NC} DONE!... Installs and updates successful${NC}\n\n"
