#!/usr/bin/env bash
#
# Shell script to install all needed development tools and software
# Run as root/sudo
#

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

echo "Install started at $(date)"
echo "Creating temp directory at /tmp/jginstall/"
mkdir -p /tmp/jginstall/
cd /tmp/jginstall/

#
# Clear the yum cache and upgrade (update and remove obsolete packages)
#
yum clean all
yum -y upgrade
yum -y install epel-release

#
# Install Basic Development Parts & General Tools
#
yum -y install yum-utils
yum -y groupinstall "Development Tools" \
"Compatibility Libraries" \
#"GNOME Desktop" \
"Security Tools" \
"System Administration Tools"
yum -y install apr-devel \
  apr-util-cdevel \
  autoconf \
  automake \
  bzip2 \
  cifs-utils \
  clang \
  clang-analyzer \
  clang-devel \
  cmake \
  curl \
  curl-devel \
  g++ \
  gcc \
  gcc-c++ \
  git-core \
  htop \
  kernel-devel \
  kernel-doc \
  llvm \
  llvm-devel \
  llvm-libs \
  make \
  nano \
  python-devel \
  python34 \
  python34-devel \
  tmux \
  vim \
  vnc-server \
  wget \
  zlib \
  zlib-devel

# Install Vim from src
# yum remove vim-enhanced vim-common vim-minimal
# git clone https://github.com/vim/vim.git
# cd vim
# ./configure --with-features=huge \
# --enable-multibyte \
# --enable-rubyinterp=yes \
# --enable-pythoninterp=yes \
# --enable-perlinterp=yes
# If installing for single user (no `make install`) VIMRUNTIMEDIR can == {vim_src}/runtime
# make VIMRUNTIMEDIR=/usr/local/share/vim/vim80
# yum install -y sudo
# sudo make install
# hash vim

# Ranger file manager
wget http://nongnu.org/ranger/ranger-stable.tar.gz
tar xvf ranger-stable.tar.gz
rm ranger-stable.tar.gz
pushd ranger-stable
make install
popd
rm -rf ranger-stable

# Mono-project repo & install
echo "Installing Mono-Project"
rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
yum-config-manager --add-repo http://download.mono-project.com/repo/centos7/
yum install -y mono-devel

# Go- remove older Go 1st (if there) then install (note DL link should be
# checked for updates)
echo "Installing go"
rm -rf /usr/local/go
wget https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
sudo tar -C /usr/local/ -xzf go1.9.linux-amd64.tar.gz

# Install Rust
echo "Installing Rust"
curl https://sh.rustup.rs -sSf | sh

#
# Server Installation Parts
#
echo "Installing server applications"
yum -y install bison \
  httpd \
  httpd-devel \
  libffi-devel \
  libtool \
  libyaml-devel \
  nodejs \
  npm \
  openssl-devel \
  patch \
  readline \
  readline-devel \
  sqlite-devel \
  vsftpd

# Open HTTP port
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=443/tcp
# Open FTP port
firewall-cmd --permanent --add-port=21/tcp
firewall-cmd --reload
systemctl enable firewalld
echo "Starting Apache"
systemctl start httpd
systemctl enable httpd

# Configure vsftpd
sed -i "s/\(anonymous_enable *= *\).*/\1NO/" /etc/vsftpd/vsftpd.conf
sed -i "s/\(local_enable *= *\).*/\1YES/" /etc/vsftpd/vsftpd.conf
sed -i "s/\(write_enable *= *\).*/\1YES/" /etc/vsftpd/vsftpd.conf
#sudo sed -i "s/\(chroot_local_user *= *\).*/\1YES/" /etc/vsftpd/vsftpd.conf
echo "Starting vsftpd FTP server"
systemctl restart vsftpd
systemctl enable vsftpd

echo "Cleaning out temp directory..."
rm -rf /tmp/jginstall/*
