#!/bin/bash
#
# Shell script to update all needed development tools
# Run as intended user
#

# mkdir's if in new system
mkdir -p ~/.vim/colors/
mkdir -p ~/.local/share/konsole/
mkdir -p ~/.config/nvim/
mkdir -p ~/.config/ranger/

# First copy local files over if they're newer
cp -u ~/.gitconfig ./configs/.gitconfig
cp -u ~/.bashrc ./configs/.bashrc
cp -u ~/.bash_profile ./configs/.bash_profile
cp -u ~/.inputrc ./configs/.inputrc
cp -u ~/.local/share/konsole/JG_profile.profile ./configs/konsole/JG_profile.profile
cp -u ~/.vimrc ./configs/.vimrc
cp -u ~/.config/nvim/init.vim ./configs/init.vim
cp -u ~/.vim/colors/monokai.vim ./configs/monokai.vim
cp -u ~/.tmux.conf ./configs/.tmux.conf
cp -u ~/.config/ranger/rc.conf ./configs/rc.conf
cp -u ~/.config/ranger/scope.sh ./configs/scope.sh
cp -u ~/.muttrc ./configs/.muttrc
cp -u ~/.ctags ./configs/.ctags
cp -u ~/.glbl_gitignore ./configs/.glbl_gitignore

# Then copy remote files over if they're newer
cp -u ./configs/.gitconfig ~/.gitconfig
cp -u ./configs/.bashrc ~/.bashrc
cp -u ./configs/.bash_profile ~/.bash_profile
cp -u ./configs/.inputrc ~/.inputrc
cp -u ./configs/konsole/JG_profile.profile ~/.local/share/konsole/JG_profile.profile
cp -u ./configs/.vimrc ~/.vimrc
cp -u ./configs/init.vim ~/.config/nvim/init.vim
cp -u ./configs/monokai.vim ~/.vim/colors/monokai.vim
cp -u ./configs/.tmux.conf ~/.tmux.conf
cp -u ./configs/rc.conf ~/.config/ranger/rc.conf
cp -u ./configs/scope.sh ~/.config/ranger/scope.sh
cp -u ./configs/.muttrc ~/.muttrc
cp -u ./configs/.ctags ~/.ctags
cp -u ./configs/.glbl_gitignore ~/.glbl_gitignore
