#!/usr/bin/env bash
#
# Shell script to update all needed development tools
# Run as intended user
#

cp ./configs/.gitconfig ~/.gitconfig
cp ./configs/.bashrc ~/.bashrc
cp ./configs/.vimrc ~/.vimrc
mkdir -p ~/.vim/colors/
cp ./configs/gmonokai.vim ~/.vim/colors/gmonokai.vim
cp ./configs/.tmux.conf ~/.tmux.conf
pushd ~/.rbenv
git pull
popd
