#!/bin/bash
#
# Shell script to update all needed development tools
# Run as intended user
#

# mkdir's if in new system
mkdir -p ~/.vim/colors/
mkdir -p ~/.config/nvim/

# First copy local files over if they're newer
cp -u ~/.gitconfig ./configs/.gitconfig
cp -u ~/.gitconfig-jcg ./configs/.gitconfig-jcg
cp -u ~/.bashrc ./configs/.bashrc
cp -u ~/.bash_profile ./configs/.bash_profile
cp -u ~/.bash_logout ./configs/.bash_logout
cp -u ~/.inputrc ./configs/.inputrc
cp -u ~/.profile ./configs/.profile
cp -u ~/.vimrc ./configs/.vimrc
cp -u ~/.vim/colors/monokai.vim ./configs/monokai.vim
cp -u ~/.tmux.conf ./configs/.tmux.conf
cp -u ~/.ctags ./configs/.ctags
cp -u ~/.glbl_gitignore ./configs/.glbl_gitignore
cp -u ~/.alacritty.toml ./configs/.alacritty.toml
cp -u  ~/.config/nvim/init.lua configs/nvim/init.lua
# Neovim has a tree of Lua files for config
cp -ur ~/.config/nvim/lua/ configs/nvim/

# Then copy remote files over if they're newer
cp -u ./configs/.gitconfig ~/.gitconfig
cp -u ./configs/.gitconfig-jcg ~/.gitconfig-jcg
cp -u ./configs/.bashrc ~/.bashrc
cp -u ./configs/.bash_profile ~/.bash_profile
cp -u ./configs/.bash_logout ~/.bash_logout
cp -u ./configs/.inputrc ~/.inputrc
cp -u ./configs/.profile ~/.profile
cp -u ./configs/.vimrc ~/.vimrc
cp -u ./configs/monokai.vim ~/.vim/colors/monokai.vim
cp -u ./configs/.tmux.conf ~/.tmux.conf
cp -u ./configs/.ctags ~/.ctags
cp -u ./configs/.glbl_gitignore ~/.glbl_gitignore
cp -u ./configs/.alacritty.toml ~/.alacritty.toml
cp -u ./configs/nvim/init.lua ~/.config/nvim/init.lua
# Neovim has a tree of Lua files for config
cp -ur ./configs/nvim/lua/ ~/.config/nvim/
