#!/bin/bash
# File              : vpn_start
# Author            : John Gentile <johncgentile17@gmail.com>
# Date              : 04.04.2018
# Last Modified Date: 04.04.2018
# Last Modified By  : John Gentile <johncgentile17@gmail.com>
#
# Script to automate Cisco VPN connection using Shew Soft VPN Client

# Default values
VpnConfig="NI-AUS"
VpnUser="$( whoami )"
# NI-dev
RemmPath="~/.remmina/1510971969859.remmina"
LaunchRemm=0

usage() { echo 'Usage: ./vpn_start [-c <VPN config name>] [-u <VPN user>] [-r <blank|path to Remmina config>]' 1>&2; exit 1; }

# Process passed in options
while getopts ":c:u:r" o; do
  case "${o}" in
    c)
      VpnConfig=${OPTARG}
      ;;
    u)
      VpnUser=${OPTARG}
      ;;
    r)
      if [ -n "${OPTARG}" ]; then
        RemmPath=${OPTARG}
      fi
      LaunchRemm=1
      ;;
    *)
      usage
      ;;
  esac
done
shift $(( OPTIND - 1 ))

# Make sure `iked` daemon is running, if not run it
if [ -z "$(pgrep iked)" ]; then
  echo "Launching Ike Daemon since not running..."
  sudo /usr/sbin/iked
fi

# Get VPN account password- POSIX compliant
stty -echo
printf "Enter VPN Password: "
read PASSWORD
stty echo
printf "\n"

# Pass credentials and config name to Ike VPN client- change where needed
printf "Connecting to VPN..."
qikec -r $VpnConfig -u $VpnUser -p $PASSWORD -a &
printf " SUCCESSFUL\n"

# If set, launch Remmina remote desktop w/config
if [ "$LaunchRemm" -eq "1" ]; then
  echo "Launching Remote Desktop..."
  # for some reason sudo is needed to load config...
  # this currently isn't working correctly
  remmina -c $RemmPath &
fi
