#!/bin/bash

rustup_out="$(rustup check)"


if [[ "$rustup_out" == *"Update available"* ]]; then
  printf " 🦀 Rust Update Available " > /tmp/rust_update_available
else
  printf "" > /tmp/rust_update_available
fi;

