#!/bin/bash
# Lists the /dev/ path of a serial USB device, aids in finding the right dev to
# open for serial comms
#   From -> https://unix.stackexchange.com/a/144735

for sysdevpath in $(find /sys/bus/usb/devices/usb*/ -name dev); do
  (
    syspath="${sysdevpath%/dev}"
    devname="$(udevadm info -q name -p $syspath)"
    [[ "$devname" == "bus/"* ]] && exit
    eval "$(udevadm info -q property --export -p $syspath)"
    [[ -z "$ID_SERIAL" ]] && exit
    echo "/dev/$devname - $ID_SERIAL"
  )
done
