#!/bin/bash
#
# Uses rsync to synchronize data drive to backup drive
# Mainly for example purposes
# (assumed files not under source control)
# `$ man rsync` for more options
#       -a, archive equals -rlptgoD
#       -v, verbose output
#       -u, skip objects that are newer on the receiver
#       --delete, delete extra objects from destination
#       --exclude './*.txt', excludes file pattern glob
#       --progress, show progress during transfer
#       --rsh=COMMAND, specify remote shell to use
#               (i.e. --rsh=ssh host::module /dest)
#

# Push: rsync folder -> remote over SSH
rsync -av --delete --progress /path/to/data/ user@server:/path/to/data/

# Push: rsync folder -> backup drive (can setup in crontab)
rsync -a --delete /path/to/data /media/backup_drive_1TB/data/ > /dev/null
