#!/bin/bash

osTyp="$(uname -s)"
if [ "$osTyp" = "Linux" ]; then
  memStr="$(free -m)"
  memVal="$(echo $memStr | awk '/Mem:/ { print int($3*1000/$2)/10 } ')"
  memUse="$(echo $memStr | awk '/Mem:/ { print int($3/10.24)/100 }')"
elif [ "$osTyp" = "Darwin" ]; then
  memStr="$(top -l 1 -s 0 | grep PhysMem)"
  memVal="$(echo $memStr | awk '{ print int(1000*$2/($2+$6))/10 }')"
  memUse="$(echo $memStr | awk '{ print int($2/10.24)/100 }')"
fi

topPs="$(ps -eo pcpu,comm,pid | sort -rn | head -n 1)"
cpuVal="$(echo "$topPs" | awk '{print $1}')"
psVal="$(echo "$topPs" | awk '{print $2 ":" $3}')"

function bar_color() {
  if (( $(echo "$1 < 12.5" | bc -l) )); then
    echo "#[fg=colour28]▁#[default]"
  elif (( $(echo "$1 < 25" | bc -l) )); then
    echo "#[fg=colour40]▂#[default]"
  elif (( $(echo "$1 < 37.5" | bc -l) )); then
    echo "#[fg=colour193]▃#[default]"
  elif (( $(echo "$1 < 50" | bc -l) )); then
    echo "#[fg=colour190]▄#[default]"
  elif (( $(echo "$1 < 62.5" | bc -l) )); then
    echo "#[fg=colour220]▅#[default]"
  elif (( $(echo "$1 < 75" | bc -l) )); then
    echo "#[fg=colour202]▆#[default]"
  elif (( $(echo "$1 < 87.5" | bc -l) )); then
    echo "#[fg=colour196]▇#[default]"
  else
    echo "#[fg=colour160]█#[default]"
  fi
}

echo -e "Mem: ${memUse}GB (${memVal}%) [$(bar_color $memVal)] | TopPs: $psVal ($cpuVal%) [$(bar_color $cpuVal)]"
