live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x585858"
blue = "0xb8b8b8"
cyan = "0xa16946"
green = "0x282828"
magenta = "0xe8e8e8"
red = "0xdc9656"
white = "0xf8f8f8"
yellow = "0x383838"

[colors.cursor]
cursor = "0xd8d8d8"
text = "0x181818"

[colors.normal]
black = "0x181818"
blue = "0x7cafc2"
cyan = "0x86c1b9"
green = "0xa1b56c"
magenta = "0xba8baf"
red = "0xab4642"
white = "0xd8d8d8"
yellow = "0xf7ca88"

[colors.primary]
background = "0x181818"
foreground = "0xd8d8d8"

# this font size is good for high-res macOS XDR display, can update
# font size live with Ctrl/Cmd +/-, and reset to this setting with 
# Ctrl/Cmd 0
[font]
size = 8.5

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

# NOTE: can launch new Alacritty windws with: Command+n
#  https://github.com/alacritty/alacritty/issues/607#issuecomment-982307003
[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[mouse]
hide_when_typing = true

[scrolling]
multiplier = 0

[window]
option_as_alt = "OnlyLeft"
